### ISSUE TITLE
Change Poll Time

### ISSUE THREAD

**Issue by tango2590** [LaggAt/ha-jokes#11]
Any chance you can allow the user to determine the poll time (either from a set list or by entering time)? Currently I get a new joke every minute. No big deal, but when I want to show someone, sometimes by the time I get to them it's already changed to a new one.

**Comment by brianewman** [comment]
I second this.  I would like hourly or even daily jokes.  My use case is two-fold:  First, I keep checking Home Assistant just to see what the joke is and it gets distracting.  Secondly, When the joke is funny, I read it to my wife and she gets annoyed because she hates dumb jokes (I love them, of course).  Having fewer jokes would distract me less and annoy my wife less. 

I was thinking of using a text helper and just copying the joke to it hourly or daily as a workaround, but having a user-selectable interval would be ideal.

**Comment by Vendo232** [comment]
agree: set refresh time variable

**Comment by tango2590** [comment]
> agree: set refresh time variable

I think adding a configuration option would be a great idea. Let the user determine when the jokes get refreshed. Unfortunately, I have no idea how to do that. I did submit a PR to update it from 60 seconds to 15 minutes though. But I like your idea of a user-set update time.

**Comment by seanmccabe** [comment]
Yer configurable time would be awesome.
Plan is to use this once a day in the morning to wake up to :)

**Comment by CarlBird** [comment]
Just change line 41 in the __init__.py file:
![Screenshot_20231203_115020_Home Assistant](https://github.com/LaggAt/ha-jokes/assets/50060909/a1e76757-0e6e-45ca-ae82-47ccdd10356b)

**Comment by mvdwetering** [comment]
The official way to change update intervals in Home Assistant nowadays is to disable the automatic updates and create an automation to trigger when you want updates.

First disable automatic polling. For this go to the integration and open the system settings for the integration (it is in the vertical 3-dot menu). There is a switch to enable polling for automatic updates. Turn off that switch.

Next create an automation that calls the `homeassitant.update_entity` service. 
This is my automation. It updates every 15 minutes, but only between 8:00 and 23:00. Change it to your liking.

```
alias: Update joke
description: ""
trigger:
  - platform: time_pattern
    minutes: /15
condition:
  - condition: time
    after: "08:00:00"
    before: "23:00:00"
    weekday:
      - sun
      - sat
      - fri
      - thu
      - wed
      - tue
      - mon
action:
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id: sensor.random_joke
mode: single
```
