### ISSUE TITLE
Add Unique ID to be able to remove sensor from recorder

### ISSUE THREAD

**Issue by Konstantin-Davidneko** [LaggAt/ha-jokes#9]
If you try to go to "Settings" of sensor.random_joke, you will see this message:
```
This entity ('sensor.random_joke') does not have a unique ID, therefore its settings cannot be managed from the UI. See the [documentation](https://www.home-assistant.io/faq/unique_id) for more detail.
```

Also, this code will not work
```yaml
recorder:
  ...
  exclude:
    entities:
      - sensor.random_joke
```

I think that it is same issue. So DB is bloated with jokes. I don't think it is common use-case, when you need history of jokes. Most people will see random joke only just now.

Can you add Unique ID  to sensor.random_joke
